services:
  item-service:
    build: ./itemservice
    container_name: item-service
    ports:
      - "8089:8089"
    networks:
      - microservices-network

  order-service:
    build: ./orderservice
    container_name: order-service
    ports:
      - "8088:8088"
    networks:
      - microservices-network

  payment-service:
    build: ./paymentservice
    container_name: payment-service
    ports:
      - "8087:8087"
    networks:
      - microservices-network

  api-gateway:
    build: ./apigateway
    container_name: api-gateway
    ports:
      - "8086:8086"
    depends_on:
      - item-service
      - order-service
      - payment-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge